/**********************************************************\ 
Original Author: Richard Bateman (taxilian)

Created:    Sept 17, 2009
License:    Eclipse Public License - Version 1.0
            http://www.eclipse.org/legal/epl-v10.html

Copyright 2009 Richard Bateman, Firebreath development team
\**********************************************************/

// FireBreathWin.idl : IDL source for FireBreathWin
//

// This file will be processed by the MIDL tool to
// produce the type library (FireBreathWin.tlb) and marshalling code.

#include "config.h"
#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(IFBControl_GUID),
    dual,
    nonextensible,
    helpstring(IFBControl_DESC),
    pointer_default(unique)
]
interface IFBControl : IDispatch{
};

[
    uuid(FBTYPELIB_GUID),
    version(1.0),
    helpstring(FBTYPELIB_DESC)
]
library FBTYPELIB_NAME
{
    importlib("stdole2.tlb");
    [
        uuid(FBControl_GUID),
        control,
        helpstring(FBControl_DESC)
    ]
    coclass FBControl
    {
        [default] interface IFBControl;
    };
};
