    [
        uuid(FBControl_GUID),
        control,
        helpstring(FBControl_DESC)
    ]
    coclass FBControl
    {
        [default] interface IFBControl;
        [default, source] dispinterface IFBComEventSource;
    };
    [
        uuid(FBControl2_GUID),
        control,
        helpstring(FBControl2_DESC)
    ]
    coclass FBControl2
    {
        [default] interface IFBControl;
        [default, source] dispinterface IFBComEventSource;
    };
