
get_filename_component (CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component (SOURCE_DIR "${CMAKE_DIR}/.." ABSOLUTE)
get_filename_component (BUILD_DIR "${CMAKE_DIR}/../build" ABSOLUTE)

set (PROJECT_ROOT "${BUILD_DIR}/projects")
set (BIN_DIR "${BUILD_DIR}/bin")

if (NOT EXISTS ${BUILD_DIR})
   file (MAKE_DIRECTORY ${BUILD_DIR})
endif()

set (FIREBREATH_SOURCE_DIR ${SOURCE_DIR})
set (FIREBREATH_BINARY_DIR ${BUILD_DIR})
set (FIREBREATH_CONFIG_DIR ${BUILD_DIR}/gen)

set (BOOST_SOURCE_DIR ${SOURCE_DIR}/3rdParty/boost)
set (GECKOSDK_SOURCE_DIR ${SOURCE_DIR}/3rdParty/gecko-sdk/win/includes)

set (ACTIVEXPLUGIN_SOURCE_DIR "${SOURCE_DIR}/ActiveXPlugin")
set (ACTIVEXPLUGIN_BINARY_DIR "${PROJECT_ROOT}/ActiveXPlugin")
set (ACTIVEXPLUGINTEST_SOURCE_DIR "${SOURCE_DIR}/ActiveXPluginTest")
set (ACTIVEXPLUGINTEST_BINARY_DIR "${PROJECT_ROOT}/ActiveXPluginTest")

set (FIREBREATHWIN_SOURCE_DIR "${SOURCE_DIR}/FireBreathWin")
set (FIREBREATHWIN_BINARY_DIR "${PROJECT_ROOT}/FireBreathWin")

set (NPAPIHOST_SOURCE_DIR "${SOURCE_DIR}/NPAPIHost")
set (NPAPIHOST_BINARY_DIR "${PROJECT_ROOT}/NPAPIHost")

set (NPAPIPLUGIN_SOURCE_DIR "${SOURCE_DIR}/NpapiPlugin")
set (NPAPIPLUGIN_BINARY_DIR "${PROJECT_ROOT}/NpapiPlugin")

set (NPAPIPLUGINTEST_SOURCE_DIR "${SOURCE_DIR}/NpapiPluginTest")
set (NPAPIPLUGINTEST_BINARY_DIR "${PROJECT_ROOT}/NpapiPluginTest")

set (SCRIPTINGCORE_SOURCE_DIR "${SOURCE_DIR}/ScriptingCore")
set (SCRIPTINGCORE_BINARY_DIR "${PROJECT_ROOT}/ScriptingCore")

set (SCRIPTINGCORETEST_SOURCE_DIR "${SOURCE_DIR}/ScriptingCoreTest")
set (SCRIPTINGCORETEST_BINARY_DIR "${PROJECT_ROOT}/ScriptingCoreTest")

set (UNITTEST_FW_SOURCE_DIR "${SOURCE_DIR}/unittest-cpp/UnitTest++")
set (UNITTEST_FW_BINARY_DIR "${PROJECT_ROOT}/UnitTest++")


