
set (FIREBREATH_SOURCE_DIR ${FB_ROOT_DIR})
set (FIREBREATH_BINARY_DIR ${BUILD_DIR})

set (BOOST_SOURCE_DIR ${SOURCE_DIR}/3rdParty/boost)
set (GECKOSDK_SOURCE_DIR ${SOURCE_DIR}/3rdParty/gecko-sdk/win/includes)

set (ACTIVEXPLUGIN_SOURCE_DIR "${SOURCE_DIR}/ActiveXPlugin")
set (ACTIVEXPLUGINTEST_SOURCE_DIR "${SOURCE_DIR}/ActiveXPluginTest")

set (NPAPIHOST_SOURCE_DIR "${SOURCE_DIR}/NPAPIHost")

set (NPAPIPLUGIN_SOURCE_DIR "${SOURCE_DIR}/NpapiPlugin")
set (NPAPIPLUGINTEST_SOURCE_DIR "${SOURCE_DIR}/NpapiPluginTest")

set (SCRIPTINGCORE_SOURCE_DIR "${SOURCE_DIR}/ScriptingCore")
set (SCRIPTINGCORETEST_SOURCE_DIR "${SOURCE_DIR}/ScriptingCoreTest")

set (PLUGINCORE_SOURCE_DIR "${SOURCE_DIR}/PluginCore")

set (UNITTEST_FW_SOURCE_DIR "${SOURCE_DIR}/unittest-cpp/UnitTest++")
set (UNITTEST_FW_BINARY_DIR "${PROJECT_ROOT}/UnitTest++")

